### ISSUE TITLE
[13] Traceback when posting a draft journal entry in a locked period instead of an error message

### ISSUE THREAD

**Issue by mylbco** [OCA/account-financial-tools#1010]
Scenario te reproduce this traceback:

POST a journal entry with a date in a locked period

<img width="566" alt="image" src="https://user-images.githubusercontent.com/3402495/84864056-56604280-b076-11ea-93ae-34578bb58859.png">

------
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/oca-addons/account-financial-tools/account_lock_to_date/models/account_move.py", line 37, in action_post
    self._check_lock_to_dates()
  File "/mnt/oca-addons/account-financial-tools/account_lock_to_date/models/account_move.py", line 15, in _check_lock_to_dates
    move.company_id.fiscalyear_lock_to_date,
TypeError: '<' not supported between instances of 'bool' and 'datetime.date'`

**Comment by AaronHForgeFlow** [comment]
This is fixed after the last merge.

**Comment by mylbco** [comment]
I'll check it out, thx !
