### ISSUE TITLE
[14.0][account_chart_update] error updating a new company

### ISSUE THREAD

**Issue by lmmar-ic** [OCA/account-financial-tools#1250]
module: account_chart_update
version: 14.0

Hi, we have a new company with PGCE PYMEs 2008 chart template, when we launch the update, then the system give us a error.

**Steps to reproduce**
new instance
install this module and All AEAT modules
run the wizard.update.charts.accounts
start with the default options

If we remove AEAT 349 the process run without problem.

**Current behavior**
Show this error:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/other-addons/account_chart_update/wizard/wizard_chart_update.py", line 309, in action_find_records
    self._find_taxes()
  File "/opt/odoo/other-addons/account_chart_update/wizard/wizard_chart_update.py", line 767, in _find_taxes
    notes = self.diff_notes(template, tax)
  File "/opt/odoo/other-addons/account_chart_update/wizard/wizard_chart_update.py", line 715, in diff_notes
    for f in self.diff_fields(template, real).keys()
  File "/opt/odoo/other-addons/account_chart_update/wizard/wizard_chart_update.py", line 689, in diff_fields
    if template_value != real[key]:
  File "/opt/odoo/odoo/odoo/models.py", line 5668, in __getitem__
    return self._fields[key].__get__(self, type(self))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'aeat_349_map_line'

**Expected behavior**
Proceed with the updates and eventually come back.

**Comment by pedrobaeza** [comment]
Remove that field in the second tab for continuing. The problem is that the field doesn't exists on both `account.tax` and `account.tax.template`, and the module doesn't handle this yet.

**Comment by lmmar-ic** [comment]
Thank you
