### ISSUE TITLE
account_menu: Error when opening users

### ISSUE THREAD

**Issue by tarbib** [OCA/account-financial-tools#1286]
module: account_menu
version: 14.0

**Steps to reproduce**
- In general Settings, click on "Manage Users"
![Peek 05-12-2021 09-56](https://user-images.githubusercontent.com/2255433/144740155-a9a9450b-cd40-4f5f-b29f-ce3850f78d7d.gif)

**Current behavior**
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/api.py", line 397, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/api.py", line 377, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-95>", line 2, in create
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/api.py", line 326, in _model_create_single
    return create(self, arg)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/addons/base/models/res_config.py", line 783, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-64>", line 2, in create
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/api.py", line 347, in _model_create_multi
    return create(self, [arg])
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/models.py", line 3826, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/sisalpuser/xoe.services/sgxz-2372/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'anglo_saxon_accounting' on model 'res.config.settings'`

**Expected behavior**
I should be able to see the users.

Additional info : 
There is no checkbox next to Anglo-Saxon accounting
![image](https://user-images.githubusercontent.com/2255433/144740206-64bf80b5-8b2c-4eb7-9189-002226a7a12f.png)

**Comment by mmequignon** [comment]
It seems that the target of the related field is missing https://github.com/OCA/account-financial-tools/blob/14.0/account_menu/models/res_config_settings.py#L10

@StefanRijnhart is that a new field, or is this coming from another module?

**Comment by RodartHub** [comment]
I have that same problem :/
