### ISSUE TITLE
[8.0] account_reset_chart: Unable to delete

### ISSUE THREAD

**Issue by alejandrosantana** [OCA/account-financial-tools#219]
@StefanRijnhart 
I have just tried to reset a chart of accounts with _account_reset_chart_ in v8.0, following the brief example in README file.
Everything OK till `client.execute('res.company', 'reset_chart', 1)`, that raises this:

```
>>> client.login('admin', admin_pw, dbname)
1
>>> client.execute('res.company', 'reset_chart', 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 693, in execute
    res = self._execute(obj, method, *params)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 383, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault warning -- Error

Unable to delete this document because it is used as a default property: ''>
```

Server log gives no warning, but they show this:

```
2015-05-25 17:51:19,807 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking vouchers.
2015-05-25 17:51:19,843 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking all records of model account.banking.account.settings for company My Company
2015-05-25 17:51:19,844 2120 INFO db_test openerp.addons.account_reset_chart: Model account.banking.account.settings not found
2015-05-25 17:51:19,844 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking all records of model res.partner.bank for company My Company
2015-05-25 17:51:19,846 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking reconciliations
2015-05-25 17:51:19,850 2120 INFO db_test openerp.addons.account_reset_chart: Reset paid invoices's workflows
2015-05-25 17:51:19,854 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking moves
2015-05-25 17:51:19,857 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking all records of model account.fiscal.position for company My Company
2015-05-25 17:51:19,890 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking all records of model account.tax for company My Company
2015-05-25 17:51:20,026 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking all records of model account.tax.code for company My Company
2015-05-25 17:51:20,208 2120 INFO db_test openerp.addons.account_reset_chart: Unlinking all records of model account.journal for company My Company
```

I tried with both the chart of accounts module installed and uninstalled, with same lack of luck.

Any idea?

**Comment by StefanRijnhart** [comment]
Yes, I believe this is fixed in the existing PR https://github.com/OCA/account-financial-tools/pull/193. Please test and review!
