### ISSUE TITLE
Transifex build failed on 8.0

### ISSUE THREAD

**Issue by guewen** [OCA/account-financial-tools#254]
Due to the following error, the Transifex build failed on eed478435800bdc1bc21db03aa43f788cdec4257:

```
Downloading PO file for account_credit_control

Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/travis_transifex.py", line 168, in <module>
    exit(main())
  File "/home/travis/maintainer-quality-tools/travis/travis_transifex.py", line 146, in main
    f.write(odoo_context.get_pot_contents(module))
  File "/home/travis/maintainer-quality-tools/travis/odoo_connection.py", line 51, in get_pot_contents
    self.trans_export(False, [addon], buf, 'po', self.cr)
  File "/home/travis/odoo-8.0/openerp/tools/translate.py", line 526, in trans_export
    _process(format, modules, translations, buffer, lang)
  File "/home/travis/odoo-8.0/openerp/tools/translate.py", line 500, in _process
    writer.write(row['modules'], row['tnrs'], src, row['translation'], row['comments'])
  File "/home/travis/odoo-8.0/openerp/tools/translate.py", line 464, in write
    % (quote(source), quote(trad))
  File "/home/travis/odoo-8.0/openerp/tools/translate.py", line 274, in quote
    assert r"\n" not in s, "Translation terms may not include escaped newlines ('\\n'), please use only literal newlines! (in '%s')" % s
AssertionError: Translation terms may not include escaped newlines ('\n'), please use only literal newlines! (in '
      Dear ${object.contact_address.name or ''}
      <br/>
      <br/>
      ${object.current_policy_level.custom_mail_text.replace('\n', '<br>') | safe}
      ')

+=======================================
|  Tests summary:
|---------------------------------------
| travis_transifex.py         FAIL
+=======================================
```

**Comment by adrienpeiffer** [comment]
Hi @guewen,
Indeed, this issue was introduced by https://github.com/OCA/account-financial-tools/pull/252.
A solution could be change the custom_mail_text field type by HTML to conserve carriage return define in this field.
What do you think ?
