### ISSUE TITLE
[7.0] [account_journal_entry_posted_async] TypeError: job() got an unexpected keyword argument 'default_channel'

### ISSUE THREAD

**Issue by manamirfhk** [OCA/account-financial-tools#365]
- module: account_journal_entry_posted_async
- version: 7.0

**Current behavior**

When clone this repository to server and start openerp-server, the following error is logged and 'No handler found' is shown on web.
Although no database has installed this module, openerp-server could not been started.

```
2016-02-25 12:27:19,412 114 CRITICAL ? openerp.modules.module: Couldn't load module web
2016-02-25 12:27:19,412 114 CRITICAL ? openerp.modules.module: job() got an unexpected keyword argument 'default_channel'
2016-02-25 12:27:19,412 114 ERROR ? openerp.service: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/service/__init__.py", line 60, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "/opt/openerp/server/openerp/modules/module.py", line 415, in load_openerp_module
    getattr(sys.modules['openerp.addons.' + module_name], info['post_load'])()
  File "/opt/openerp/server/openerp/addons/web/http.py", line 628, in wsgi_postload
    openerp.wsgi.register_wsgi_handler(Root())
  File "/opt/openerp/server/openerp/addons/web/http.py", line 517, in __init__
    self.load_addons()
  File "/opt/openerp/server/openerp/addons/web/http.py", line 580, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/openerp/server/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/openerp/addons/account-financial-tools/account_journal_entry_posted_async/__init__.py", line 2, in <module>
    from . import models
  File "/opt/openerp/addons/account-financial-tools/account_journal_entry_posted_async/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/opt/openerp/addons/account-financial-tools/account_journal_entry_posted_async/models/account_move.py", line 58, in <module>
    @job(default_channel='root.account_move_validate')
TypeError: job() got an unexpected keyword argument 'default_channel'
```

config file is as follows.

```
[options]
addons_path = openerp/addons,../addons/e-commerce,../addons/connector,../addons/connector-magento,../addons/product-attribute,../addons/sale-workflow,../addons/connector-ecommerce,../addons/partner-contact,../addons/account-financial-tools
admin_passwd = ******
csv_internal_sep = ,
db_host = 
db_maxconn = 64
db_name = False
db_password = ******
db_port = False
db_template = template1
db_user = openerp
dbfilter = .*
debug_mode = False
demo = {}
email_from = False
import_partial =
limit_memory_hard = 805306368
limit_memory_soft = 671088640
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
list_db = True
log_handler = [':INFO']
log_level = info
logfile = /var/log/openerp/openerp-server.log
login_message = False
logrotate = True
max_cron_threads = 2
netrpc = False
netrpc_interface =
netrpc_port = 8070
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = True
reportgz = False
secure_cert_file = server.cert
secure_pkey_file = server.pkey
server_wide_modules = web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
static_http_document_root = None
static_http_enable = False
static_http_url_prefix = None
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
timezone = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 0
xmlrpc = True
xmlrpc_interface =
xmlrpc_port = 8069
xmlrpcs = True
xmlrpcs_interface =
xmlrpcs_port = 8071
odoo_connector_channels = root:4,root.account_move_validate:1
```

@lmignon If you have ideas, could you please let me know the reason and how to deal with it?

**Comment by guewen** [comment]
2 things:
1. What version of the `connector` addon do you use? According to the traceback, I think it is too old.
2. `ODOO_CONNECTOR_CHANNELS` is an environment variable not an option of the configuration file

**Comment by guewen** [comment]
Misread, I didn't see that you didn't installed the addon. Could you try with this patch? https://github.com/OCA/account-financial-tools/pull/364

**Comment by manamirfhk** [comment]
Thanks @guewen 
I understood `ODOO_CONNECTOR_CHANNELS` is not an option of .conf file

I tried the patch #364, but encountered the same error..

**Comment by guewen** [comment]
I think you have an out-dated version of `connector` in your addons-path.

**Comment by manamirfhk** [comment]
@guewen OK, thanks. There maybe things to be checked by us. I will get back to this.

**Comment by manamirfhk** [comment]
I agreed our `connector` repository is too old. We decide to remove this module from the repository, or add only modules in the repository that we will use.
I will close this issue. Thanks!
