### ISSUE TITLE
[11.0] error to compute items into loan 

### ISSUE THREAD

**Issue by cesarsc79** [OCA/account-financial-tools#748]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/account-financial-tools/account_loan/model/account_loan.py", line 368, in compute_lines
    return self.compute_draft_lines()
  File "/home/odoo/build/OCA/account-financial-tools/account_loan/model/account_loan.py", line 437, in compute_draft_lines
    self.check_long_term_principal_amount()
  File "/home/odoo/build/OCA/account-financial-tools/account_loan/model/account_loan.py", line 393, in check_long_term_principal_amount
    final_sequence = min(lines.mapped('sequence'))
ValueError: min() arg is an empty sequence

**Comment by cesarsc79** [comment]
runbot error

**Comment by bodedra** [comment]
We can close these issue as PR is merged.
