### ISSUE TITLE
[11.0] account_credit_control fails if no attachment on e-mail template

### ISSUE THREAD

**Issue by robin5210** [OCA/account-financial-tools#887]
When trying to send e-mail when a template without report to attach is selected. The following error is emited:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/client/parts/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/client/parts/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/client/parts/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/client/parts/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/client/parts/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/client/parts/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/client/parts/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/client/parts/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/client/parts/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/client/parts/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/client/parts/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/client/parts/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/client/parts/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/client/parts/oca/account-financial-tools/account_credit_control/models/credit_control_run.py", line 210, in run_channel_action
    comms._generate_emails()
  File "/opt/odoo/client/parts/oca/account-financial-tools/account_credit_control/wizard/credit_control_communication.py", line 193, in _generate_emails
    }) for att in attachment_list]
TypeError: 'NoneType' object is not iterable
```

My guess is the error is introduced in `wizard/credit_control_communication.py` on L 174.
The default case should be an empty list.

**Comment by pedrobaeza** [comment]
Can you propose a PR for solving that problem?
