### ISSUE TITLE
[12.0][account_asset_management] local fiscal year incompatible

### ISSUE THREAD

**Issue by hioppolo-ia** [OCA/account-financial-tools#918]
Since the module is configured for the European fiscal year, when we tried to deploy it into one of our test databases with an Australian fiscal year (1 July – 30 June), it gave an error when calculating depreciation on the depreciation board of an asset.

I imagine this error would impact all other users with different fiscal years (USA, Canada, Australia, UK or any country other than 1 Jan – 31 Dec etc.). 

Would anyone consider collaborating to make this module compatible for other fiscal years?
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/OCA/account-financial-tools/account_asset_management/account_asset_management/models/account_asset.py", line 463, in compute_depreciation_board
    table = asset._compute_depreciation_table()
  File "/home/odoo/src/user/OCA/account-financial-tools/account_asset_management/account_asset_management/models/account_asset.py", line 925, in _compute_depreciation_table
    table, line_dates,
  File "/home/odoo/src/user/OCA/account-financial-tools/account_asset_management/account_asset_management/models/account_asset.py", line 779, in _compute_depreciation_amount_per_fiscal_year
    entry, firstyear)
  File "/home/odoo/src/user/OCA/account-financial-tools/account_asset_management/account_asset_management/models/account_asset.py", line 625, in _get_fy_duration_factor
    fy, option='years')
  File "/home/odoo/src/user/OCA/account-financial-tools/account_asset_management/account_asset_management/models/account_asset.py", line 599, in _get_fy_duration
    datetime(year, 12, 31) - fy_date_start).days + 1
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
```

**Comment by mmotahar** [comment]
It's not only wrong for Australia but for any localisation with a different fiscal year settings. So in summary this module does NOT calculate the depreciation if the fiscal year is changed. It only works for 1st Jan to 31 Dec (European fiscal year). 

 Interesting that no one has reported this before.
